// <auto-generated />
using System;
using EnigmaVault.Secret.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnigmaVault.Secret.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnigmaContext))]
    [Migration("20251106120744_Update_DeleteBehavior_Folder_Conf")]
    partial class Update_DeleteBehavior_Folder_Conf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FolderName")
                        .UseCollation("case_insensitive");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("ParentFolderId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders", (string)null);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.Icon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IconCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("IconCategoryId");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IconName")
                        .UseCollation("case_insensitive");

                    b.Property<string>("SvgCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SvgCode");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IconCategoryId");

                    b.ToTable("Icons", (string)null);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.IconCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name")
                        .UseCollation("case_insensitive");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("IconCategories", (string)null);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.Folder", b =>
                {
                    b.HasOne("EnigmaVault.Secret.Domain.Models.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.Icon", b =>
                {
                    b.HasOne("EnigmaVault.Secret.Domain.Models.IconCategory", null)
                        .WithMany()
                        .HasForeignKey("IconCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
