// <auto-generated />
using System;
using EnigmaVault.Secret.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnigmaVault.Secret.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnigmaContext))]
    partial class EnigmaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FolderName")
                        .UseCollation("case_insensitive");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("ParentFolderId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders", (string)null);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name")
                        .UseCollation("case_insensitive");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.VaultItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("CryptoVersion")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_version");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateAdded");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateUpdated");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("EncryptedDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EncryptedDetails");

                    b.Property<string>("EncryptedOverview")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EncryptedOverview");

                    b.Property<Guid>("IconId")
                        .HasColumnType("uuid")
                        .HasColumnName("IconId");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsArchive");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFavorite");

                    b.Property<bool>("IsInTrash")
                        .HasColumnType("boolean")
                        .HasColumnName("IsInTrash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<int>("VaultType")
                        .HasColumnType("integer")
                        .HasColumnName("VaultType");

                    b.HasKey("Id");

                    b.ToTable("VaultItems", (string)null);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.VaultTags", b =>
                {
                    b.Property<Guid>("VaultItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_item_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("VaultItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("vault_tags", (string)null);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.Folder", b =>
                {
                    b.HasOne("EnigmaVault.Secret.Domain.Models.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.VaultTags", b =>
                {
                    b.HasOne("EnigmaVault.Secret.Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnigmaVault.Secret.Domain.Models.VaultItem", null)
                        .WithMany("Tags")
                        .HasForeignKey("VaultItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnigmaVault.Secret.Domain.Models.VaultItem", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
